名称：日常任务

于：

  

  推：＃推触发

    分支机构：[主要]

  workflow_dispatch：＃手动触发

  时间表：＃计划任务触发

    - cron的：' * / 30 20-23,0-15 * * * '  ＃ cron的表达式，操作时区是UTC时间，所以要往前推8个小时（4-23）

    

职位：

  日常任务：

    如果：github.event.repository.owner.id == github.event.sender.id

    env：

      ENABLE_52POJIE：$ {{ secrets.ENABLE_52POJIE }}

      ENABLE_BILIBILI：$ {{secrets.ENABLE_BILIBILI}}

      ENABLE_IQIYI：$ {{secrets.ENABLE_IQIYI}}

      ENABLE_UNICOM：$ {{ secrets.ENABLE_UNICOM }}

    

    运行：ubuntu-latest

    策略：

      矩阵：

        节点版本：[12]

        节点注册表：['https://registry.npmjs.org']

    步骤：

    

    ＃检出

    -名称：结帐

      用途：actions / checkout @ v2

      

    ＃设置服务器时区为东八区

    -名称：设置时区

      运行：sudo timedatectl设置时区'亚洲/上海'

    -名称：使用Node.js $ {{matrix.node-version}}

      用途：actions / setup-node @ v1

      与：

        节点版本：$ {{matrix.node-version}}

        注册表网址：$ {{matrix.node-registry}}

    -名称：获取npm缓存目录

      id：npm缓存

      运行：|

        echo“ :: set-output name = dir :: $（npm配置获取缓存）”

    -名称：恢复npm缓存

      用途：acti
